### ISSUE TITLE
define not found error

### ISSUE THREAD

**Issue by casser** [systemjs/plugin-text#23]
Plugin is not working with SystemJs (v0.19.6), jspm (0.16.15), typescript (1.7.3), any ideas why it using amd format ? 
Usage
```javascript
import template from "./login.html";
```

or

```javascript
import template from "./login.html!text";
```
Config mapping 
```javascript
{
//...
meta: {
    "*.html": {
      "loader": "text"
    }
},
map:{
    "text": "github:systemjs/plugin-text@0.0.3"
    //...
}
//...
}
```
Translated code
```javascript
(function(System) {(function(__moduleName){System.register([], function(exports_1) {
    return {
        setters:[],
        execute: function() {
            define(function () {
                return "...html stringified text......";
            });
        }
    }
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJza......NBQUMifQ==
})("http://localhost:3000/sources/views/auth/login.html!http://localhost:3000/packages/github/systemjs/plugin-text@0.0.3.js");
})(System);
```
Error
```
TypeError: define is not a function
    at execute (login.html:1)
    at u (system.src.js:4597)
    at u (system.src.js:4597)
    at Object.execute (system.src.js:4597)
    at y (system.src.js:4597)
    at w (system.src.js:4597)
    at p (system.src.js:4597)
    at h (system.src.js:4597)
    at system.src.js:4597
```

**Comment by guybedford** [comment]
This is due to the incorrect translation happening on the plugin output.

I've added https://github.com/systemjs/plugin-text/commit/9f90936137d894eed104c090518030d1f308e024 to enforce the format and pushed out an updated release. Let me know if that works for you?
